### ISSUE TITLE
Pokemon API

### ISSUE THREAD

**Issue by wfknowles** [ddcrane/pokemon-trading-post#19]
*Documentation

**Comment by bpkaufman4** [comment]
{
    "id": "swsh4-25",
    "name": "Charizard",
    "supertype": "Pokémon",
    "hp": "170",
    "types": [
      "Fire"
    ],
    "evolvesFrom": "Charmeleon",
    "abilities": [
      {
        "name": "Battle Sense",
        "text": "Once during your turn, you may look at the top 3 cards of your deck and put 1 of them into your hand. Discard the other cards.",
        "type": "Ability"
      }
    ],
    "attacks": [
      {
        "name": "Royal Blaze",
        "cost": [
          "Fire",
          "Fire"
        ],
        "convertedEnergyCost": 2,
        "damage": "100+",
        "text": "This attack does 50 more damage for each Leon card in your discard pile."
      }
    ],
    "weaknesses": [
      {
        "type": "Water",
        "value": "×2"
      }
    ],
    "set": {
      "id": "swsh4",
      "name": "Vivid Voltage",
      "series": "Sword & Shield",
      "printedTotal": 185,
      "total": 203,
      "legalities": {
        "unlimited": "Legal",
        "standard": "Legal",
        "expanded": "Legal"
      },
      "ptcgoCode": "VIV",
      "releaseDate": "2020/11/13",
      "updatedAt": "2020/11/13 16:20:00",
      "images": {
        "symbol": "https://images.pokemontcg.io/swsh4/symbol.png",
        "logo": "https://images.pokemontcg.io/swsh4/logo.png"
      }
    },
    "number": "25",
    "artist": "Ryuta Fuse",
    "rarity": "Rare",
    "flavorText": "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.",
    "nationalPokedexNumbers": [
      6
    ],
    "images": {
      "small": "https://images.pokemontcg.io/swsh4/25.png",
      "large": "https://images.pokemontcg.io/swsh4/25_hires.png"
    }
}
